data_source mongo:
  type: mongodb
  connection:
    host: ${MONGO_HOST:mongodb}
    port: ${MONGO_PORT:27017}
    username: ${MONGO_USERNAME:admin}
    password: ${MONGO_PASSWORD:password123}
    database: ${MONGO_DATABASE:youtube_data}
    auth_database: admin

# Configuration locale (pas de Soda Cloud requis)
soda_cloud:
  # Configuration optionnelle pour Soda Cloud
  # Laissé vide pour exécution locale
  host: 
  api_key_id: 
  api_key_secret:
